DROP TABLE transaction;
DROP TABLE types;
DROP TABLE account;
CREATE TABLE Account
  (
    Name       VARCHAR(50) NOT NULL ,
    Balance    NUMBER NOT NULL,
    AccNum     INTEGER PRIMARY KEY,
    type       VARCHAR(50),
    feeCharged NUMBER
  );
CREATE TABLE Types
  (
    typeID INTEGER generated BY DEFAULT ON NULL AS identity PRIMARY KEY,
    type   VARCHAR(50) NOT NULL
  );
CREATE TABLE Transaction
  (
    typeID        INTEGER NOT NULL,
    Amount        NUMBER NOT NULL,
    AccNum        INTEGER NOT NULL,
    curdate       DATE NOT NULL,
    status        VARCHAR(50) NOT NULL,
    transactionID INTEGER generated BY DEFAULT ON NULL AS identity PRIMARY KEY
  );
ALTER TABLE transaction ADD CONSTRAINT type_fk FOREIGN KEY (typeID) REFERENCES types(typeID);
ALTER TABLE transaction ADD CONSTRAINT acc_fk FOREIGN KEY (AccNum) REFERENCES account(AccNum);
INSERT INTO types
  (type
  ) VALUES
  ('Check'
  );
INSERT INTO types
  (type
  ) VALUES
  ('Debit card'
  );
INSERT INTO types
  (type
  ) VALUES
  ('Deposit'
  );
INSERT INTO types
  (type
  ) VALUES
  ('Withdrawal'
  );
COMMIT;



-----
SELECT * FROM types;
SELECT* FROM account;
SELECT * FROM transaction;
UPDATE transaction SET Status = 'New';
COMMIT;
UPDATE account SET balance = 100 WHERE accnum = 1234;
SELECT DISTINCT accnum, balance FROM account;
SELECT * FROM transaction WHERE status = 'New';
SELECT a.no_of_transaction,
  b.no_of_deposits,
  c.total_deposits,
  d.no_of_withdrawls,
  e.total_withdrawals,
  f.fee_charged,
  g.no_of_checkingacc,
  h.no_of_savingacc
FROM
  (SELECT COUNT(DISTINCT transactionid) AS no_of_transaction FROM transaction
  ) a,
  (SELECT COUNT(DISTINCT transactionid) AS no_of_deposits
  FROM transaction
  WHERE TYPEID=3
  ) b,
  (SELECT SUM(amount) AS total_deposits FROM transaction WHERE TYPEID=3
  ) c,
  (SELECT COUNT(DISTINCT transactionid) AS no_of_withdrawls
  FROM transaction
  WHERE TYPEID=4
  ) d,
  (SELECT SUM(amount) AS total_withdrawals FROM transaction WHERE TYPEID=4
  ) e,
  (SELECT SUM(feecharged) AS fee_charged FROM account
  ) f,
  (SELECT COUNT(DISTINCT accnum) AS no_of_checkingacc
  FROM account
  WHERE type ='C'
  ) g,
  (SELECT COUNT(DISTINCT accnum) AS no_of_savingacc
  FROM account
  WHERE type ='S'
  ) h;
SELECT a.no_of_transaction,
  b.no_of_deposits,
  c.total_deposits,
  d.no_of_withdrawls,
  e.total_withdrawals,
  f.fee_charged,
  g.no_of_checkingacc,
  h.no_of_savingacc
FROM
  (SELECT COUNT(DISTINCT transactionid) AS no_of_transaction FROM transaction
  ) a,
  (SELECT COUNT(DISTINCT transactionid) AS no_of_deposits
  FROM transaction
  WHERE TYPEID=3
  ) b,
  (SELECT SUM(amount) AS total_deposits FROM transaction WHERE TYPEID=3
  ) c,
  (SELECT COUNT(DISTINCT transactionid) AS no_of_withdrawls
  FROM transaction
  WHERE TYPEID=4
  ) d,
  (SELECT SUM(amount) AS total_withdrawals FROM transaction WHERE TYPEID=4
  ) e,
  (SELECT SUM(feecharged) AS fee_charged FROM account
  ) f,
  (SELECT COUNT(DISTINCT accnum) AS no_of_checkingacc
  FROM account
  WHERE type ='C'
  ) g,
  (SELECT COUNT(DISTINCT accnum) AS no_of_savingacc
  FROM account
  WHERE type ='S'
  ) h,
  (SELECT DISTINCT name FROM account WHERE accnum = 1235
  ) e; 