DROP TABLE "ORA1"."BHPOST";
DROP TABLE "ORA1"."BHUSER";
--------------------------------------------------------
--  DDL for Table BHPOST
--------------------------------------------------------

  CREATE TABLE "ORA1"."BHPOST"
   (    "POSTID" NUMBER --GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE 
   ,
    "POSTDATE" DATE not NULL,
    "POSTTEXT" VARCHAR2(141 BYTE) not NULL,
    "BHUSERID" NUMBER not NULL,
    parentId Number default -1,
    likes Integer default 0
   ) ;
--------------------------------------------------------
--  DDL for Table BHUSER
--------------------------------------------------------

  CREATE TABLE "ORA1"."BHUSER"
   (    "BHUSERID" NUMBER --GENERATED BY DEFAULT ON NULL AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE 
   ,
    "USERNAME" VARCHAR2(50 BYTE) not null,
    "USERPASSWORD" VARCHAR2(50 BYTE) not null,
    "MOTTO" VARCHAR2(100 BYTE) DEFAULT NULL,
    "USEREMAIL" VARCHAR2(100 BYTE) not null,
    "JOINDATE" DATE not NULL,
    url varchar2(200) not null
   ) ;
REM INSERTING into ORA1.BHPOST
SET DEFINE OFF;
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (1,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 8',2);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (2,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 1',1);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (3,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 2',2);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (4,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 3',3);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (5,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 4',4);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (6,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 5',4);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (7,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 6',3);
Insert into ORA1.BHPOST (POSTID,POSTDATE,POSTTEXT,BHUSERID) values (8,to_date('16-JUN-16','DD-MON-RR'),'This is a sample post 7',1);
REM INSERTING into ORA1.BHUSER
SET DEFINE OFF;
Insert into ORA1.BHUSER (BHUSERID,USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE,url) values (1,'user 1','password','motto for user 1','user1@domain.com',to_date('16-JUN-16','DD-MON-RR'),'https://www.gravatar.com/avatar/3bc81bc52e7f209c3455af320abeee00?s=');
Insert into ORA1.BHUSER (BHUSERID,USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE,url) values (2,'user 2','password','motto for user 2','user2@domain.com',to_date('16-JUN-16','DD-MON-RR'),'https://www.gravatar.com/avatar/ed076488b22b5359d7ffb16b8e30caed?s=');
Insert into ORA1.BHUSER (BHUSERID,USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE,url) values (3,'user 3','password','motto for user 3','user3@domain.com',to_date('16-JUN-16','DD-MON-RR'),'https://www.gravatar.com/avatar/2435c2893e394a7de1173e5014c4ea69?s=');
Insert into ORA1.BHUSER (BHUSERID,USERNAME,USERPASSWORD,MOTTO,USEREMAIL,JOINDATE,url) values (4,'user 4','password','motto for user 4','user4@domain.com',to_date('16-JUN-16','DD-MON-RR'),'https://www.gravatar.com/avatar/8068c1de40b9cbeb487d5c3402bac34c?s=');
--------------------------------------------------------
--  DDL for Index BHPOST_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."BHPOST_PK" ON "ORA1"."BHPOST" ("POSTID")
  ;
--------------------------------------------------------
--  DDL for Index BHUSER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "ORA1"."BHUSER_PK" ON "ORA1"."BHUSER" ("BHUSERID")
  ;
--------------------------------------------------------
--  Constraints for Table BHPOST
--------------------------------------------------------

  ALTER TABLE "ORA1"."BHPOST" ADD CONSTRAINT "BHPOST_PK" PRIMARY KEY ("POSTID")
  USING INDEX  ENABLE;
  ALTER TABLE "ORA1"."BHPOST" MODIFY ("POSTID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table BHUSER
--------------------------------------------------------

  ALTER TABLE "ORA1"."BHUSER" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "ORA1"."BHUSER" MODIFY ("USERPASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ORA1"."BHUSER" MODIFY ("USEREMAIL" NOT NULL ENABLE);
  ALTER TABLE "ORA1"."BHUSER" ADD CONSTRAINT "BHUSER_PK" PRIMARY KEY ("BHUSERID")
  USING INDEX  ENABLE;
  ALTER TABLE "ORA1"."BHUSER" MODIFY ("BHUSERID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table BHPOST
--------------------------------------------------------

  ALTER TABLE "ORA1"."BHPOST" ADD CONSTRAINT "FK_BHUSERID" FOREIGN KEY ("BHUSERID")
      REFERENCES "ORA1"."BHUSER" ("BHUSERID") DEFERRABLE INITIALLY DEFERRED ENABLE;



drop SEQUENCE bhuser_id_seq;
drop SEQUENCE bhpost_id_seq;



create sequence bhuser_id_seq start with 5 increment by 1 nocache;
create sequence bhpost_id_seq start with 9 increment by 1 nocache;

commit;

select * from  bhuser;
select * from  bhpost;
  
SELECT BHPOST_ID_SEQ.NEXTVAL FROM DUAL;

SELECT bhuser_id_seq.NEXTVAL FROM DUAL;


delete from bhuser where USERNAME = 'Navreet';
delete from bhpost where posttext =' ';

select * from bhpost where posttext like '%Hel%';