DROP TABLE replacementMap;
DROP TABLE hedgeSet;
DROP TABLE qualifierSet;
CREATE TABLE replacementMap
  (
    id      NUMBER generated BY DEFAULT ON NULL AS identity PRIMARY KEY,
    input   VARCHAR2(50) NOT NULL UNIQUE,
    REPLACE VARCHAR2(50) NOT NULL
  );
INSERT INTO REPLACEMENTMAP
  (input,REPLACE
  ) VALUES
  ('my','your'
  );
INSERT INTO REPLACEMENTMAP
  (input,REPLACE
  ) VALUES
  ('me','you'
  );
INSERT INTO REPLACEMENTMAP
  (input,REPLACE
  ) VALUES
  ('i','you'
  );
INSERT INTO REPLACEMENTMAP
  (input,REPLACE
  ) VALUES
  ('am','are'
  );
INSERT INTO REPLACEMENTMAP
  (input,REPLACE
  ) VALUES
  ('you','i'
  );
INSERT INTO REPLACEMENTMAP
  (input,REPLACE
  ) VALUES
  ('your','my'
  );
CREATE TABLE hedgeSet
  (
    id       NUMBER generated BY DEFAULT ON NULL AS identity PRIMARY KEY,
    question VARCHAR2(200) NOT NULL UNIQUE
  );
INSERT INTO hedgeSet
  (question
  ) VALUES
  ('Please tell me more'
  );
INSERT
INTO hedgeSet
  (
    question
  )
  VALUES
  (
    'Many of my patients tell me the same thing'
  );
INSERT
INTO hedgeSet
  (
    question
  )
  VALUES
  (
    'It is getting late, maybe we had better quit'
  );
CREATE TABLE qualifierSet
  (
    id       NUMBER generated BY DEFAULT ON NULL AS identity PRIMARY KEY,
    question VARCHAR2(200) NOT NULL UNIQUE
  );
INSERT INTO qualifierSet
  (question
  ) VALUES
  ('Why do you say that'
  );
INSERT INTO qualifierSet
  (question
  ) VALUES
  ('You seem to think that'
  );
INSERT INTO qualifierSet
  (question
  ) VALUES
  ('So, you are concerned that'
  );
COMMIT;